language: node_js
node_js: "6"
os:
- linux
- osx
dist: trusty
osx_image: xcode8.3
sudo: false

addons:
  apt:
    packages:
    - fakeroot
    - rpm

script:
- npm run lint
- npm run make
after_success: if test -n "$TRAVIS_TAG"; then npm run publish; fi
