name: Build

on:
  push:
    # Uses your default branch on first init;
    # This should be manually reset to your repo's default branch
    # branches: [$default-branch]
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # 3.1.0
      - name: Setup Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
        with:
          node-version: 18.x
          cache: yarn
      - name: Install
        run: yarn
      - name: lint
        run: yarn lint
  package:
    needs: lint
    runs-on: ${{ matrix.host }}
    strategy:
      matrix:
        host: [windows-latest, macOS-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # 3.1.0
      - name: Setup Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
        with:
          node-version: 18.x
          cache: yarn
      - name: Package App
        run: yarn package
  make:
    needs: package
    runs-on: ${{ matrix.host }}
    strategy:
      matrix:
        host: [windows-latest, macOS-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # 3.1.0
      - name: Setup Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
        with:
          node-version: 18.x
          cache: yarn
      - name: Make App
        run: yarn make
      - name: Save distributable
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v.3.1.1
        with:
          name: my-artifact
          path: out/make
          if-no-files-found: warn